vich_uploader:
    db_driver: orm

    mappings:
        artisticWork_image:
            uri_prefix: /images/artisticWorks
            upload_destination: '%kernel.project_dir%/public/images/artisticWorks'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
